#!/bin/bash
if pgrep  "Adobe Lightroom" >/dev/null
then
   echo "Cannot continue since Adobe Lightroom is running."
   exit 1
fi

#rsync -Partv ~/lightroom ~/backup1
#rsync -Partv ~/lightroom ~/backup2
#rsync -Partv ~/lightroom ~/backup3
#rsync -Partv ~/lightroom ~/backup5
#rsync -Partv ~/lightroom ~/backup6
#rsync -Partv /Volumes/16TBA/original-images /Volumes/8TBC

rsync -Partv ~/lightroom /Volumes/NVME03
rsync -Partv ~/lightroom /Volumes/16TBA
rsync -Partv ~/lightroom /Volumes/16TBB
rsync -Partv ~/lightroom /Volumes/4TBA
rsync -Partv ~/lightroom /Volumes/4TBB
