#!/bin/bash
if pgrep  "prl_client_app" >/dev/null
then
   echo "Cannot continue since Parallels is running."
   exit 1
fi

if pgrep  "VMware Fusion" >/dev/null
then
   echo "Cannot continue since VMware Fusion is running."
   exit 1
fi

HOSTNAME=`hostname`

if [[ "$HOSTNAME" == m4* ]]; then
   TARGETS="FAST1 FAST3"
   export SRC="/Volumes/FAST1/vmware-vms"
elif [[ "$HOSTNAME" == m3* ]]; then
   TARGETS="FAST1 FAST3"   
elif [[ "$HOSTNAME" == m1* ]]; then
   TARGETS="4TBC"
   export SRC="/Users/$USER/vmware-vms"
else
   echo "Unknown hostname. Exiting."
   exit 1
fi

# Hostname may end with a domain, which can be "local" or "lan" (it can switch
# between the two). For predictability, we'll use just the first token from
# HOSTNAME if it contains a period.
if [[ "$HOSTNAME" == *.* ]]; then
   export JUST_HOST_NAME="${HOSTNAME%%.*}"
else
   export JUST_HOST_NAME="$HOSTNAME"
fi

echo ${JUST_HOST_NAME}

if [ ! -d "$SRC" ]; then
   echo "Source directory $SRC does not exist. Exiting."
   exit 1
fi

for TARGET in $TARGETS; do
   echo "Backing up to $TARGET"
   DEST="/Volumes/$TARGET/$JUST_HOST_NAME"
   mkdir -p "$DEST"
   rsync -Partv --exclude '.DS_Store' "$SRC" "$DEST"
done
