#!/bin/bash
if pgrep  "prl_client_app" >/dev/null
then
   echo "Cannot continue since Parallels is running."
   exit 1
fi

rsync -Part ~/Parallels ~/fastA
rsync -Part ~/Parallels ~/fastB
rsync -Part ~/Parallels ~/slowC
rsync -Part ~/Parallels ~/localA
rsync -Part ~/Parallels ~/localB
rsync -Part ~/Parallels ~/localC
