#!/bin/bash
set -e
if pgrep  "prl_client_app" >/dev/null
then
   echo "Cannot continue since Parallels is running."
   exit 1
fi

if pgrep  "VMware Fusion" >/dev/null
then
   echo "Cannot continue since VMware Fusion is running."
   exit 1
fi

mount_tnas_all.sh
HOSTNAME=`hostname`

# Hostname may end with a domain, which can be "local" or "lan" (it can switch
# between the two). For predictability, we'll use just the first token from
# HOSTNAME if it contains a period.
if [[ "$HOSTNAME" == *.* ]]; then
   export JUST_HOST_NAME="${HOSTNAME%%.*}"
else
   export JUST_HOST_NAME="$HOSTNAME"
fi

echo ${JUST_HOST_NAME}

if [[ "$HOSTNAME" == m4* ]]; then
   TARGETS="public"
   export SRC="/Volumes/FAST1/$JUST_HOST_NAME/vmware-vms"
elif [[ "$HOSTNAME" == m1* ]]; then
   TARGETS="public"
   export SRC="/Users/$USER/vmware-vms"
else
   echo "Unknown hostname. Expected hostname to start with m1 or m4, got $HOSTNAME. Exiting."
   exit 1
fi


if [ ! -d "$SRC" ]; then
   echo "Source directory $SRC does not exist. Exiting."
   exit 1
fi

for TARGET in $TARGETS; do
   echo "Backing up to $TARGET"
   DEST="/Volumes/$TARGET/$JUST_HOST_NAME"
   mkdir -p "$DEST"
   rsync -Partv --exclude '.DS_Store' $SRC "$DEST"
done
