#!/bin/bash
if pgrep  "prl_client_app" >/dev/null
then
   echo "Cannot continue since Parallels is running."
   exit 1
fi

if pgrep  "VMware Fusion" >/dev/null
then
   echo "Cannot continue since VMware Fusion is running."
   exit 1
fi

SRC=FAST2
rsync -Part /Volumes/$SRC/vmware-vms ~/localA
rsync -Part /Volumes/$SRC/vmware-vms ~/localB
rsync -Part /Volumes/$SRC/vmware-vms ~/localC
rsync -Part /Volumes/$SRC/vmware-vms ~/slowC

rsync -Part ~/"Virtual Machines.localized" ~/localA
rsync -Part ~/"Virtual Machines.localized" ~/localB
rsync -Part ~/"Virtual Machines.localized" ~/localC
rsync -Part ~/"Virtual Machines.localized" ~/slowC

rsync -Part ~/Parallels ~/slowC
rsync -Part ~/Parallels ~/localA
rsync -Part ~/Parallels ~/localB
rsync -Part ~/Parallels ~/localC
