#!/bin/bash
set -e
TEMPDIR=$(mktemp -d)
docker image list | cut -d' ' -f1 | grep -v REPOSITORY | while read -r line; do
    safe_line=$(echo "$line" | sed 's/\//__/g')
    docker save "$line" -o "$TEMPDIR/$safe_line.tar"
done
tar -czf docker-images.tar.gz -C "$TEMPDIR" .
rm -rf "$TEMPDIR"