#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from github_release import gh_asset
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(gh_asset())
