#!/bin/bash
#CGO_ENABLED=1 go build --ldflags='-extldflags=-static -w -s -X main.version=$tag' -tags osusergo,netgo,sqlite_omit_load_extension "$@"
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static" -w' "$@"
