#!/bin/bash
unset GO111MODULE
unset GOFLAGS
unset GOPATH
export PATH=~/go/bin:$PATH

go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install golang.org/x/tools/cmd/goimports@latest

