#!/bin/bash
set -e
if pgrep  "VMware Fusion" >/dev/null
then
   echo "Cannot continue since VMware Fusion is running."
   exit 1
fi
if pgrep "prl_client_app" >/dev/null
then
   echo "Cannot continue since Parallels is running."
   exit 1
fi
export EXTBASE=~/backup1
htoq2
export EXTBASE=~/backup4
htoq2
export EXTBASE=~/backup6
htoq2


#rsync -Partv backup1/Parallels backup2
#rsync -Partv backup1/Parallels backup3
#rsync -Partv backup1/Parallels backup4
