#!/bin/bash
mkdir -p ~/dev/github.com/lf8r
cd ~/dev/github.com/lf8r
export GOFLAGS=-mod=mod
export GOROOT=/usr/local/go
export GO111MODULE=on
export GOPRIVATE=github.com/hpe-hcss,github.com/quattronetworks,github.com/lf8r
