#!/bin/bash
fusermount3 -u /var/tmp/documents
sshfs sdasgupta@192.168.86.150:/Volumes/8TBA/data/genai/documents /var/tmp/documents -C
fusermount3 -u /var/tmp/report-data
sshfs sdasgupta@192.168.86.150:/Volumes/8TBA/data/bigdata/mediahuis/report-data /var/tmp/report-data -C
fusermount3 -u /var/tmp/logs
sshfs sdasgupta@192.168.86.150:/Volumes/8TBA/data/bigdata/logs /var/tmp/logs -C