#!/bin/bash
set -e

#OLLAMA_CONTEXT_LENGTH=262144
#OLLAMA_CONTEXT_LENGTH=131072
OLLAMA_CONTEXT_LENGTH=131072 OLLAMA_MLX=1 OLLAMA_HOST="0.0.0.0" OLLAMA_KEEP_ALIVE=5m OLLAMA_NUM_PARALLEL=4 OLLAMA_DEBUG=BUG=1 OLLAMA_FLASH_ATTENTION="1"  OLLAMA_MODELS="/var/tmp/models" ollama serve 2>&1 | tee -a ~/.ollama/logs/server.log
echo $! > ~/.ollama/pid