#!/bin/bash
set -e
cd $QUAKE/controllers/rackcontroller/main
echo "Building rack controller"
./build.sh
scp main ubuntu@images.hpedemo.net:.
cd ../../serviceclient/main
echo "Building service client"
./build.sh
scp sc ubuntu@images.hpedemo.net:.
