#!/bin/sh
for f in *.jpg;
do
	echo Processing $f
	echo $f
	FILENAME=$f
	# Set variable for the current filename
	CURRENTIMAGE=$f
	MODEL=`magick $CURRENTIMAGE -format "%[exif:Model]" info:`
	CAPTURE_TIME=`magick $CURRENTIMAGE -format "%[exif:DateTimeOriginal]" info:`
	CAPTURE_TIME=$(echo $CAPTURE_TIME | sed 's/ /@/')
	EXPOSURE=`magick $CURRENTIMAGE -format "%[exif:FNumber]" info:`
	SPEED=`magick $CURRENTIMAGE -format "%[exif:ExposureTime]" info:`
	LENS=`magick $CURRENTIMAGE -format "%[exif:LensModel]" info:`
	ISO=`magick $CURRENTIMAGE -format "%[exif:PhotographicSensitivity]" info:`
	IMAGE_NUMBER=`exiftool $CURRENTIMAGE | grep "Image Number"`
	POS=$(exiftool "$f" | grep "GPS Position")
	POS=$(echo "$POS" | sed 's/GPS Position//')
	POS=$(echo "$POS" | sed 's/^ *//')
	POS=$(echo "$POS" | sed 's/^://')
	POS=$(echo "$POS" | sed 's/^ *//')
	echo $POS
	if [ -z "$POS" ]; then
		POS="--"
	fi
	magick mogrify -border 150x150 -pointsize 60 -font Helvetica -bordercolor "#000000" -fill white -gravity north -annotate +100+12 "S U B H A J I T   D A S G U P T A\nR E F L E C T I O N S" -font Helvetica -pointsize 60 -fill white -gravity south -annotate +100+12 "$f | ${CAPTURE_TIME} | ${POS}" $f;
done
