#!/bin/sh
set -e
go clean -cache -modcache -testcache
sudo vmware-toolbox-cmd disk shrink /
#rm -rf $HOME/.lemminx
#rm -rf $HOME/.cache/go-build
#docker system prune --all --force
#sudo journalctl --vacuum-time=10d
#dd if=/dev/zero of=zerofillfile bs=1M
#rm zerofillfile

