#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: $0 <private_key_file>"
    exit 1
fi
KEY_FILE="$1"
if [ ! -f "$KEY_FILE" ]; then
    echo "Error: Private key file '$KEY_FILE' does not exist. Trying with $HOME/.ssh/id_rsa_$KEY_FILE"
    KEY_FILE="$HOME/.ssh/id_rsa_$KEY_FILE"
    echo $KEY_FILE
fi
if [ ! -f "$KEY_FILE" ]; then
    echo "Error: Private key file '$KEY_FILE' does not exist. Trying with $HOME/.ssh/id_rsa_$KEY_FILE"
    KEY_FILE = "$HOME/.ssh/id_rsa_$KEY_FILE"
fi
eval "$(ssh-agent -s)"
ssh-add $KEY_FILE