#!/bin/bash
# set -e

# Parse command line arguments
if [ $# -gt 0 ]; then
    JUMP_STATION="$1"
else
    read -p "Please provide the JUMP_STATION (the host from which Ollama is accessible): " JUMP_STATION
fi

if [ $# -gt 1 ]; then
    OLLAMA_PROVIDER="$2"
else
    OLLAMA_PROVIDER="localhost"
fi

if [ $# -gt 2 ]; then
    LOCAL_PORT="$3"
else
    LOCAL_PORT="11434"
fi

# Set USER from hostname if not set
if [ -z "$USER" ]; then
    USER=$(whoami)
fi
export USER

# Kill any other tunnels processes that are using the same local por
pkill -f "ssh -f -N -q -L 0.0.0.0:11434:localhost:11434"
# SSH tunnel command
ssh -f -N -q -L 0.0.0.0:${LOCAL_PORT}:${OLLAMA_PROVIDER}:${LOCAL_PORT} ${JUMP_STATION}
curl --silent --show-error --fail http://localhost:${LOCAL_PORT}